### ISSUE TITLE
How can I open a USB POS-printer on windows?

### ISSUE THREAD

**Issue by leedstyh** [kenshaw/escpos#15]
As the title says, I'm not sure how to connect to the POS-printer that on a USB port, windows 7

Thanks

**Comment by leedstyh** [comment]
Hi @vizcay 

Try using zadig to install drivers for your printer.

http://zadig.akeo.ie

**Comment by vizcay** [comment]
Hi @leedstyh, great I see.. but how do you print with this library after that?

I mean, in linux we just use file descriptors: ```f, err := os.Open("/dev/usb/lp3")```.. but in Windows how you connect to the usb endpoint? because as far as I understand this golang lib doesn't talks "libusb" as the README page states.

**Comment by DrPrykhodko** [comment]
Any progress of that?

**Comment by kenshaw** [comment]
This is not likely to ever work on Windows. Please talk to Microsoft about this.
