### ISSUE TITLE
Disable logging by default

### ISSUE THREAD

**Issue by damdo** [kenshaw/escpos#22]
First of all, thanks for this library.
One thing I noticed while using it is that it is quite chatty in that it logs every time it write any bytes to the printer.

Here:
https://github.com/kenshaw/escpos/blob/81d0344e35fafe5bda5dc2b6adf43d8abcff36c7/escpos.go#L92

and here:
https://github.com/kenshaw/escpos/blob/81d0344e35fafe5bda5dc2b6adf43d8abcff36c7/escpos.go#L95

I think this is quite useful for certain cases but quite noisy for most of the other cases, where this level of logging might not be necessary/needed.

Thus I'd like to propose if we could make the logging optional and have some sort of configuration option to enable it when needed.

Alternatively we could use the `int` already returned by `WriteRaw` (which is currently always returning 0), and return the number of bytes that have been written so then the caller can log the result if interested.

How does this sound?
Thanks

**Comment by damdo** [comment]
Any thoughts @kenshaw? Thanks!

**Comment by kenshaw** [comment]
Sure, just submit a PR. I don't use this library myself anymore, as the project I hacked it together for is long finished.

**Comment by damdo** [comment]
Hey @kenshaw
I've implemented some little improvements to the repo (modules, lightweight CI) and the disabled logging by default changes that we discussed, here: #24 and #23 (this one depends on #24). Please take a look.
Thanks.

**Comment by kenshaw** [comment]
@damdo Thanks for the changes. This was one of the earlier packages I wrote, and was still becoming familiar with Go at the time. Suffice to say, I would not have written anything like this in the last 6 years or so.

**Comment by kenshaw** [comment]
@damdo I rebased #23 -- please rebase #24 against the new head, and I'll add it to the repo.
